<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_SignalGen" Id="{9e442db7-209c-4d8a-90b5-bb041717cfa9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SignalGen
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_SignalGen">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>