<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Int_Trig" Id="{55810532-8985-4c11-bc26-6b43280535c6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Int_Trig
VAR_INPUT
	IN:INT;
END_VAR
VAR_OUTPUT
	Q:BOOL;
END_VAR
VAR
	M:INT;
END_VAR
(*neste bloco funcional a saida Q e ativa durante um ciclo toda vez que ocorre uma mudanca na variavel IN*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[Q:=IN<>M;
M:=IN;]]></ST>
    </Implementation>
    <LineIds Name="FB_Int_Trig">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>