<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="trigTesting" Id="{29ebff99-8be7-45d6-9419-bdb8c4d4b454}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM trigTesting
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="trigTesting">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>