<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Sample" Id="{2aa8f178-7ea8-4256-b8d2-7cd95ddd0a8b}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'reflection'} 
FUNCTION_BLOCK FB_Sample 
VAR 
    {attribute 'instance-path'} 
    {attribute 'noinit'} 
    sPath : STRING; 
END_VAR 
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Sample">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>