<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Teste" Id="{66e009f7-7c1e-46b8-ac1e-3cc645133fb7}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'reflection'} 
FUNCTION_BLOCK FB_Teste
VAR
    {attribute 'instance-path'} 
    {attribute 'noinit'} 
	varTeste:STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Teste">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>