<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{f714639e-05df-4447-a78a-06a7cf813137}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	r1:LREAL:=20;
    fbSample : FB_Sample; 
    sMyPath : STRING; 
	teste:FB_Teste;
	grupo:FB_GroupDiag;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[safetyDiag();
fbSample(); 
sMyPath := fbSample.sPath; ]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>