<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{0e9e55d4-2d89-4609-847a-11769322b6a8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	avanca AT %Q*: BOOL;
	recua AT %Q*: BOOL;
	sensorAvancado AT %I*: BOOL;
	sensorRecuado AT %I*: BOOL;
	posicao AT %I*: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>