<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{077b38a9-d9d0-4582-9d08-e7ea990f2571}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	dt1:DT;
	r1:REAL;
	r2:LREAL;
	i1:INT;
	i2:UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[prgTrigTesting();
prgTestAuxsFuns();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="20" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>